# Generated by Django 5.0.6 on 2024-06-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Facturacion.metodopago'),
            preserve_default=False,
        ),
    ]
