# Generated by Django 5.0.6 on 2024-05-12 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id_codigo_postal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_postal', models.IntegerField()),
                ('localidad', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Código postal',
                'verbose_name_plural': 'Códigos postales',
                'db_table': 'codigo_postal',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_postal', models.ForeignKey(db_column='id_codigo_postal', on_delete=django.db.models.deletion.CASCADE, to='Envio.codigopostal')),
                ('usuario', models.OneToOneField(db_column='id_usuarios', on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envio',
            },
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='Envio.provincia'),
        ),
    ]
