# Generated by Django 5.0.6 on 2024-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('contrasena', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('dni', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('nro_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
